import Navbar from "@/components/Navbar";
import "./globals.css";
import Loading from "./loading";
import { Suspense } from "react";

import localFont from "next/font/local";

const NeueMontreal = localFont({
  src: "../public/font/NeueMontreal-Regular.otf",
  variable: "--neue-Montreal",
});

const neuebit = localFont({
  src: "../public/font/NeueBit-Regular.ttf",
  variable: "--neue-bit",
});

export const metadata = {
  title: "Personal Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${neuebit.variable} ${NeueMontreal.variable} flex justify-center`}>
        <Navbar />
        <Suspense fallback={<Loading />}>
          {children}
          {/* <Page /> */}
        </Suspense>
      </body>
    </html>
  );
}
